version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 10
    assignees: ["vreshch"]
    groups:
      all-dependencies:
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 5
    assignees: ["vreshch"]
    groups:
      all-dependencies:
        patterns: ["*"]
